// <auto-generated />
namespace VirtoCommerce.CartModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CartNewTotalsAndTax : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartNewTotalsAndTax));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061251293_CartNewTotalsAndTax"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
