// <auto-generated />
namespace VirtoCommerce.CartModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCartType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCartType));
        
        string IMigrationMetadata.Id
        {
            get { return "201803120853157_AddCartType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
