// <auto-generated />
namespace VirtoCommerce.CartModule.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ManyCoupons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyCoupons));
        
        string IMigrationMetadata.Id
        {
            get { return "201809051333524_ManyCoupons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
